development:
 adapter: mysql2
 database: developmentdb
 username: root
 password: TG19052003
 host: localhost
 encoding: utf8
 pool: 5

test:
 database: testdb
 adapter: mysql2
 encoding: utf8
 username: root
 password: TG19052003
 host: localhost
 pool: 5

production:
 adapter: mysql2
 database: Railsdb
 username: root
 password: TG19052003
 host: localhost
 encoding: utf8
 pool: 5